const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);const $=s=>document.querySelector(s);const money=n=>Number(n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});const msg=t=>{const x=$("#adminMsg");if(x)x.textContent=t};
async function isAdmin(){const {data:{user}}=await sb.auth.getUser();if(!user)return false;const {data,error}=await sb.from("profiles").select("role").eq("id",user.id).single();return !error&&data?.role==="admin"}
async function boot(){if(await isAdmin())showPanel();else{$("#adminLogin").classList.remove("hidden");$("#adminPanel").classList.add("hidden")}}
function showPanel(){$("#adminLogin").classList.add("hidden");$("#adminPanel").classList.remove("hidden");loadProducts();loadOrders()}
$("#adminAuth").addEventListener("submit",async e=>{e.preventDefault();const {error}=await sb.auth.signInWithPassword({email:$("#adminEmail").value.trim(),password:$("#adminPassword").value});if(error){msg(error.message);return}if(!(await isAdmin())){await sb.auth.signOut();msg("Esta conta não tem permissão de administrador.");return}showPanel()});
$("#adminLogout").addEventListener("click",async()=>{await sb.auth.signOut();location.reload()});document.querySelectorAll("[data-tab]").forEach(b=>b.addEventListener("click",()=>{const t=b.dataset.tab;$("#adminProducts").classList.toggle("hidden",t!=="products");$("#adminOrders").classList.toggle("hidden",t!=="orders")}));
async function loadProducts(){const {data}=await sb.from("products").select("id,name,description,price,stock,image_url,active,sizes,featured,tag,icon,categories(name)").order("created_at",{ascending:false});$("#adminProductList").innerHTML=(data||[]).map(p=>`<div class="order-card"><div><strong>${p.name}</strong><span>${p.categories?.name||""}</span></div><p>${money(p.price)} · estoque ${p.stock} · ${p.active?"Ativo":"Inativo"}</p><div class="account-actions"><button class="btn btn-outline" onclick='editProduct(${JSON.stringify(p).replace(/'/g,"&#39;")})'>Editar</button><button class="btn btn-outline" onclick="toggleProduct(${p.id},${p.active})">${p.active?"Ocultar":"Ativar"}</button></div></div>`).join("")||'<div class="empty-state">Nenhum produto.</div>'}
window.editProduct=p=>{$("#productId").value=p.id;$("#productName").value=p.name;$("#productCategory").value=p.categories?.name||"Camisetas";$("#productPrice").value=p.price;$("#productStock").value=p.stock;$("#productSizes").value=(p.sizes||[]).join(", ");$("#productImage").value=p.image_url||"";$("#productDescription").value=p.description||"";$("#productTag").value=p.tag||"";$("#productIcon").value=p.icon||"👕";$("#productFeatured").checked=!!p.featured;window.scrollTo({top:0,behavior:"smooth"})};
window.toggleProduct=async(id,active)=>{const {error}=await sb.from("products").update({active:!active}).eq("id",id);if(error)msg(error.message);else loadProducts()};
$("#productForm").addEventListener("submit",async e=>{e.preventDefault();const id=$("#productId").value;const category=$("#productCategory").value;const {data:cat}=await sb.from("categories").select("id").eq("name",category).single();const row={name:$("#productName").value.trim(),category_id:cat.id,price:Number($("#productPrice").value),stock:Number($("#productStock").value),sizes:$("#productSizes").value.split(",").map(x=>x.trim()).filter(Boolean),image_url:$("#productImage").value.trim()||null,description:$("#productDescription").value.trim(),tag:$("#productTag").value.trim()||null,icon:$("#productIcon").value.trim()||"👕",featured:$("#productFeatured").checked,active:true};const result=id?await sb.from("products").update(row).eq("id",id):await sb.from("products").insert(row);if(result.error)msg(result.error.message);else{msg("Produto salvo.");$("#productForm").reset();$("#productId").value="";$("#productIcon").value="👕";loadProducts()}});$("#clearProduct").addEventListener("click",()=>{$("#productForm").reset();$("#productId").value="";$("#productIcon").value="👕"});
async function loadOrders(){const {data,error}=await sb.from("orders").select("id,status,total,payment_method,created_at,profiles(full_name,email),order_items(product_name,quantity,unit_price,size)").order("created_at",{ascending:false});if(error){$("#adminOrderList").innerHTML=`<p class="muted">${error.message}</p>`;return}$("#adminOrderList").innerHTML=(data||[]).map(o=>`<div class="order-card"><div><strong>Pedido #${o.id}</strong><span>${new Date(o.created_at).toLocaleString("pt-BR")}</span></div><p>${o.profiles?.full_name||"Cliente"} · ${o.profiles?.email||""}</p><p>${(o.order_items||[]).map(i=>`${i.product_name} (${i.size||"Único"}) × ${i.quantity}`).join(" · ")}</p><strong>${money(o.total)}</strong><select onchange="updateStatus(${o.id},this.value)"><option ${o.status==="recebido"?"selected":""}>recebido</option><option ${o.status==="em_preparacao"?"selected":""}>em_preparacao</option><option ${o.status==="enviado"?"selected":""}>enviado</option><option ${o.status==="entregue"?"selected":""}>entregue</option><option ${o.status==="cancelado"?"selected":""}>cancelado</option></select></div>`).join("")||'<div class="empty-state">Nenhum pedido.</div>'}
window.updateStatus=async(id,status)=>{const {error}=await sb.from("orders").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(error)msg(error.message);else loadOrders()};boot();
