-- JMG STORE - upgrade para produtos, favoritos, pedidos e painel administrativo
-- Execute este arquivo no Supabase SQL Editor.

alter table public.profiles add column if not exists role text not null default 'customer' check (role in ('customer','admin'));
alter table public.products add column if not exists sizes text[] not null default '{}';
alter table public.products add column if not exists featured boolean not null default false;
alter table public.products add column if not exists tag text;
alter table public.products add column if not exists icon text default '👕';
alter table public.order_items add column if not exists size text;
alter table public.orders add column if not exists payment_method text;
alter table public.orders add column if not exists whatsapp_sent boolean not null default false;
alter table public.orders add column if not exists updated_at timestamptz not null default now();

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(user_id, product_id)
);

create index if not exists products_category_idx on public.products(category_id);
create index if not exists products_active_idx on public.products(active);
create index if not exists favorites_user_idx on public.favorites(user_id);
create index if not exists orders_user_idx on public.orders(user_id);
create index if not exists order_items_order_idx on public.order_items(order_id);

alter table public.favorites enable row level security;

drop policy if exists "Users can select own favorites" on public.favorites;
drop policy if exists "Users can insert own favorites" on public.favorites;
drop policy if exists "Users can delete own favorites" on public.favorites;
create policy "Users can select own favorites" on public.favorites for select using (auth.uid() = user_id);
create policy "Users can insert own favorites" on public.favorites for insert with check (auth.uid() = user_id);
create policy "Users can delete own favorites" on public.favorites for delete using (auth.uid() = user_id);

-- Permite ao cliente criar e consultar seus próprios pedidos/itens.
drop policy if exists "Users can select own orders" on public.orders;
drop policy if exists "Users can insert own orders" on public.orders;
drop policy if exists "Users can select own order items" on public.order_items;
drop policy if exists "Users can insert own order items" on public.order_items;
create policy "Users can select own orders" on public.orders for select using (auth.uid() = user_id);
create policy "Users can insert own orders" on public.orders for insert with check (auth.uid() = user_id);
create policy "Users can select own order items" on public.order_items for select using (exists (select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid()));
create policy "Users can insert own order items" on public.order_items for insert with check (exists (select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid()));

-- Função segura para saber se o usuário atual é administrador.
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.profiles where id = auth.uid() and role = 'admin');
$$;

-- Políticas administrativas. Apenas usuários cujo profiles.role = admin podem usar o painel.
drop policy if exists "Admins can manage products" on public.products;
create policy "Admins can manage products" on public.products for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can manage categories" on public.categories;
create policy "Admins can manage categories" on public.categories for all using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can read all profiles" on public.profiles;
create policy "Admins can read all profiles" on public.profiles for select using (auth.uid() = id or public.is_admin());

drop policy if exists "Admins can read all orders" on public.orders;
create policy "Admins can read all orders" on public.orders for select using (auth.uid() = user_id or public.is_admin());

drop policy if exists "Admins can update orders" on public.orders;
create policy "Admins can update orders" on public.orders for update using (public.is_admin()) with check (public.is_admin());

drop policy if exists "Admins can read all order items" on public.order_items;
create policy "Admins can read all order items" on public.order_items for select using (exists (select 1 from public.orders o where o.id = order_id and (o.user_id = auth.uid() or public.is_admin())));

drop policy if exists "Admins can read all addresses" on public.addresses;
create policy "Admins can read all addresses" on public.addresses for select using (auth.uid() = user_id or public.is_admin());

-- Produtos de teste. Só serão inseridos se ainda não houver produtos.
insert into public.categories (name) values ('Camisetas'), ('Blusas'), ('Bonés'), ('Pochetes') on conflict (name) do nothing;

insert into public.products (category_id,name,description,price,stock,image_url,active,sizes,featured,tag,icon)
select c.id, x.name, x.description, x.price, x.stock, null, true, x.sizes, x.featured, x.tag, x.icon
from (values
 ('Camisetas','Camiseta Fé & Propósito','Modelo de teste da coleção JMG.',79.90,10,array['P','M','G','GG'],true,'Destaque','👕'),
 ('Camisetas','Camiseta Graça','Modelo de teste da coleção JMG.',79.90,8,array['P','M','G','GG'],true,'Novo','👕'),
 ('Blusas','Blusa Caminho','Modelo de teste da coleção JMG.',119.90,6,array['P','M','G','GG'],true,'Destaque','🧥'),
 ('Blusas','Blusa Faith','Modelo de teste da coleção JMG.',119.90,7,array['P','M','G','GG'],false,'Novo','🧥'),
 ('Bonés','Boné JMG','Modelo de teste da coleção JMG.',59.90,12,array['Único'],false,null,'🧢'),
 ('Bonés','Boné Fé','Modelo de teste da coleção JMG.',59.90,9,array['Único'],false,null,'🧢'),
 ('Pochetes','Pochete JMG','Modelo de teste da coleção JMG.',69.90,11,array['Único'],false,null,'🎒'),
 ('Pochetes','Pochete Propósito','Modelo de teste da coleção JMG.',69.90,5,array['Único'],false,null,'🎒')
) as x(category,name,description,price,stock,sizes,featured,tag,icon)
join public.categories c on c.name = x.category
where not exists (select 1 from public.products p where p.name = x.name);

-- Para transformar sua conta em administradora, troque o e-mail abaixo e execute:
-- update public.profiles set role = 'admin' where email = 'SEU_EMAIL_AQUI';
