-- =========================================================
-- JMG STORE - SQL COMPLETO ATUALIZADO
-- Produtos, favoritos, pedidos, clientes e painel admin
-- Suporte a múltiplos administradores (2 admins configuráveis)
-- =========================================================
-- IMPORTANTE:
-- 1) As tabelas principais já devem existir: profiles, addresses,
--    categories, products, orders e order_items.
-- 2) Antes de executar, edite os 2 e-mails na seção 24.
-- =========================================================

-- =========================================================
-- 1. PERFIL / ROLE
-- =========================================================
alter table public.profiles
add column if not exists role text not null default 'customer';

-- Garante valores válidos em role sem recriar a tabela.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_role_check'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_role_check
      check (role in ('customer','admin'));
  end if;
end $$;

-- =========================================================
-- 2. CAMPOS DOS PRODUTOS
-- =========================================================
alter table public.products
add column if not exists sizes text[] not null default '{}';

alter table public.products
add column if not exists featured boolean not null default false;

alter table public.products
add column if not exists tag text;

alter table public.products
add column if not exists icon text default '👕';

-- =========================================================
-- 3. CAMPOS DOS PEDIDOS
-- =========================================================
alter table public.orders
add column if not exists payment_method text;

alter table public.orders
add column if not exists whatsapp_sent boolean not null default false;

alter table public.orders
add column if not exists updated_at timestamptz not null default now();

-- =========================================================
-- 4. TAMANHO DOS ITENS DO PEDIDO
-- =========================================================
alter table public.order_items
add column if not exists size text;

-- =========================================================
-- 5. FAVORITOS
-- =========================================================
create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(user_id, product_id)
);

-- =========================================================
-- 6. ÍNDICES
-- =========================================================
create index if not exists products_category_idx on public.products(category_id);
create index if not exists products_active_idx on public.products(active);
create index if not exists favorites_user_idx on public.favorites(user_id);
create index if not exists orders_user_idx on public.orders(user_id);
create index if not exists order_items_order_idx on public.order_items(order_id);
create index if not exists addresses_user_idx on public.addresses(user_id);

-- =========================================================
-- 7. FUNÇÃO DE ADMIN
-- =========================================================
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
set row_security = off
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role = 'admin'
  );
$$;

-- =========================================================
-- 8. PROTEÇÃO DO CAMPO ROLE
-- =========================================================
-- Impede um cliente autenticado de se transformar em admin
-- alterando o próprio profile pela API.
create or replace function public.protect_profile_role()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Chamadas administrativas do SQL Editor / service role têm auth.uid() nulo.
  if auth.uid() is null then
    return new;
  end if;

  if tg_op = 'INSERT' then
    if coalesce(new.role, 'customer') <> 'customer' and not public.is_admin() then
      raise exception 'Somente administradores podem definir role=admin';
    end if;
  elsif tg_op = 'UPDATE' then
    if new.role is distinct from old.role and not public.is_admin() then
      raise exception 'Somente administradores podem alterar o nível de acesso';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists profiles_protect_role on public.profiles;
create trigger profiles_protect_role
before insert or update on public.profiles
for each row
execute function public.protect_profile_role();

-- =========================================================
-- 9. ATIVAR RLS
-- =========================================================
alter table public.profiles enable row level security;
alter table public.addresses enable row level security;
alter table public.categories enable row level security;
alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.favorites enable row level security;

-- =========================================================
-- 10. RLS - FAVORITOS
-- =========================================================
drop policy if exists "Users can view own favorites" on public.favorites;
drop policy if exists "Users can add own favorites" on public.favorites;
drop policy if exists "Users can delete own favorites" on public.favorites;
drop policy if exists "Users can select own favorites" on public.favorites;
drop policy if exists "Users can insert own favorites" on public.favorites;
drop policy if exists "Users can delete own favorites" on public.favorites;

create policy "Users can view own favorites"
on public.favorites
for select
to authenticated
using (user_id = auth.uid());

create policy "Users can add own favorites"
on public.favorites
for insert
to authenticated
with check (user_id = auth.uid());

create policy "Users can delete own favorites"
on public.favorites
for delete
to authenticated
using (user_id = auth.uid());

-- =========================================================
-- 11. RLS - PRODUTOS
-- =========================================================
drop policy if exists "Anyone can view active products" on public.products;
drop policy if exists "Admins can manage products" on public.products;

create policy "Anyone can view active products"
on public.products
for select
to anon, authenticated
using (active = true);

create policy "Admins can manage products"
on public.products
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- =========================================================
-- 12. RLS - CATEGORIAS
-- =========================================================
drop policy if exists "Anyone can view categories" on public.categories;
drop policy if exists "Admins can manage categories" on public.categories;

create policy "Anyone can view categories"
on public.categories
for select
to anon, authenticated
using (true);

create policy "Admins can manage categories"
on public.categories
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- =========================================================
-- 13. RLS - PROFILES
-- =========================================================
drop policy if exists "Admins can manage profiles" on public.profiles;
drop policy if exists "Admins can read all profiles" on public.profiles;
drop policy if exists "Users can view own profile" on public.profiles;
drop policy if exists "Users can insert own profile" on public.profiles;
drop policy if exists "Users can update own profile" on public.profiles;

create policy "Admins can manage profiles"
on public.profiles
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy "Users can view own profile"
on public.profiles
for select
to authenticated
using (id = auth.uid() or public.is_admin());

create policy "Users can insert own profile"
on public.profiles
for insert
to authenticated
with check (id = auth.uid());

create policy "Users can update own profile"
on public.profiles
for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

-- =========================================================
-- 14. RLS - ENDEREÇOS
-- =========================================================
drop policy if exists "Users can view own addresses" on public.addresses;
drop policy if exists "Users can create own addresses" on public.addresses;
drop policy if exists "Users can update own addresses" on public.addresses;
drop policy if exists "Admins can read all addresses" on public.addresses;

create policy "Users can view own addresses"
on public.addresses
for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

create policy "Users can create own addresses"
on public.addresses
for insert
to authenticated
with check (user_id = auth.uid());

create policy "Users can update own addresses"
on public.addresses
for update
to authenticated
using (user_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or public.is_admin());

-- =========================================================
-- 15. RLS - PEDIDOS
-- =========================================================
drop policy if exists "Users can view own orders" on public.orders;
drop policy if exists "Users can create own orders" on public.orders;
drop policy if exists "Users can select own orders" on public.orders;
drop policy if exists "Users can insert own orders" on public.orders;
drop policy if exists "Admins can read all orders" on public.orders;
drop policy if exists "Admins can manage orders" on public.orders;
drop policy if exists "Admins can update orders" on public.orders;
drop policy if exists "Admins can manage all orders" on public.orders;

create policy "Users can view own orders"
on public.orders
for select
to authenticated
using (user_id = auth.uid() or public.is_admin());

create policy "Users can create own orders"
on public.orders
for insert
to authenticated
with check (user_id = auth.uid());

create policy "Admins can manage orders"
on public.orders
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- =========================================================
-- 16. RLS - ITENS DOS PEDIDOS
-- =========================================================
drop policy if exists "Users can view own order items" on public.order_items;
drop policy if exists "Users can create own order items" on public.order_items;
drop policy if exists "Users can select own order items" on public.order_items;
drop policy if exists "Users can insert own order items" on public.order_items;
drop policy if exists "Admins can read all order items" on public.order_items;
drop policy if exists "Admins can manage order items" on public.order_items;

create policy "Users can view own order items"
on public.order_items
for select
to authenticated
using (
  exists (
    select 1
    from public.orders o
    where o.id = order_items.order_id
      and (o.user_id = auth.uid() or public.is_admin())
  )
);

create policy "Users can create own order items"
on public.order_items
for insert
to authenticated
with check (
  exists (
    select 1
    from public.orders o
    where o.id = order_items.order_id
      and o.user_id = auth.uid()
  )
);

create policy "Admins can manage order items"
on public.order_items
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

-- =========================================================
-- 17. CATEGORIAS PADRÃO
-- =========================================================
insert into public.categories (name)
values
  ('Camisetas'),
  ('Blusas'),
  ('Bonés'),
  ('Pochetes')
on conflict (name) do nothing;

-- =========================================================
-- 18. PRODUTOS DE TESTE
-- =========================================================
insert into public.products
(category_id,name,description,price,stock,image_url,active,sizes,featured,tag,icon)
select
  c.id,
  x.name,
  x.description,
  x.price,
  x.stock,
  null,
  true,
  x.sizes,
  x.featured,
  x.tag,
  x.icon
from (values
  ('Camisetas','Camiseta Fé & Propósito','Modelo de teste da coleção JMG.',79.90,10,array['P','M','G','GG']::text[],true,'Destaque','👕'),
  ('Camisetas','Camiseta Graça','Modelo de teste da coleção JMG.',79.90,8,array['P','M','G','GG']::text[],true,'Novo','👕'),
  ('Blusas','Blusa Caminho','Modelo de teste da coleção JMG.',119.90,6,array['P','M','G','GG']::text[],true,'Destaque','🧥'),
  ('Blusas','Blusa Faith','Modelo de teste da coleção JMG.',119.90,7,array['P','M','G','GG']::text[],false,'Novo','🧥'),
  ('Bonés','Boné JMG','Modelo de teste da coleção JMG.',59.90,12,array['Único']::text[],false,null,'🧢'),
  ('Bonés','Boné Fé','Modelo de teste da coleção JMG.',59.90,9,array['Único']::text[],false,null,'🧢'),
  ('Pochetes','Pochete JMG','Modelo de teste da coleção JMG.',69.90,11,array['Único']::text[],false,null,'🎒'),
  ('Pochetes','Pochete Propósito','Modelo de teste da coleção JMG.',69.90,5,array['Único']::text[],false,null,'🎒')
) as x(category,name,description,price,stock,sizes,featured,tag,icon)
join public.categories c on c.name = x.category
where not exists (
  select 1
  from public.products p
  where p.name = x.name
);

-- =========================================================
-- 19. PADRONIZAR STATUS ANTIGOS
-- =========================================================
-- O site e o painel passam a gravar os valores internos em inglês,
-- enquanto a interface continua mostrando os textos em português.
update public.orders
set status = case status
  when 'recebido' then 'received'
  when 'preparando' then 'preparing'
  when 'enviado' then 'shipped'
  when 'concluído' then 'completed'
  when 'cancelado' then 'cancelled'
  else status
end
where status in ('recebido','preparando','enviado','concluído','cancelado');

-- =========================================================
-- 20. UPDATED_AT AUTOMÁTICO
-- =========================================================
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at
before update on public.orders
for each row
execute function public.set_updated_at();

-- =========================================================
-- 21. GARANTIR QUE O ADMIN POSSA ALTERAR ROLES PELO PAINEL
-- =========================================================
-- A política "Admins can manage profiles" + o trigger de proteção
-- permitem que somente administradores promovam/rebaixem usuários.

-- =========================================================
-- 22. CORREÇÃO DE PERFIS QUE EXISTEM NO AUTH MAS NÃO EM PROFILES
-- =========================================================
-- Nenhuma ação geral é feita aqui para não criar perfis indesejados.
-- A seção 24 abaixo cria/atualiza apenas as 2 contas administrativas.

-- =========================================================
-- 23. OBSERVAÇÃO SOBRE OS 2 ADMINS
-- =========================================================
-- As duas contas precisam existir primeiro em:
-- Supabase > Authentication > Users
--
-- Depois, edite SOMENTE os dois e-mails na seção 24.

-- =========================================================
-- 24. DEFINIR OS 2 ADMINISTRADORES
-- =========================================================
do $$
declare
  admin_emails text[] := array[
    'PRIMEIRO_ADMIN@gmail.com',
    'SEGUNDO_ADMIN@gmail.com'
  ];
  found_count integer;
begin
  -- Se os placeholders não forem alterados, o restante do SQL continua,
  -- mas nenhuma conta é promovida por engano.
  if admin_emails[1] = 'PRIMEIRO_ADMIN@gmail.com'
     or admin_emails[2] = 'SEGUNDO_ADMIN@gmail.com' then
    raise notice 'ATENÇÃO: edite os 2 e-mails da seção 24 antes de configurar os administradores.';
    return;
  end if;

  insert into public.profiles (id,email,full_name,phone,role)
  select
    u.id,
    u.email,
    coalesce(nullif(u.raw_user_meta_data->>'full_name',''),'Administrador'),
    coalesce(u.raw_user_meta_data->>'phone',''),
    'admin'
  from auth.users u
  where lower(u.email) = any (
    array[
      lower(admin_emails[1]),
      lower(admin_emails[2])
    ]
  )
  on conflict (id)
  do update set
    email = excluded.email,
    role = 'admin';

  select count(*)
  into found_count
  from auth.users u
  where lower(u.email) = any (
    array[
      lower(admin_emails[1]),
      lower(admin_emails[2])
    ]
  );

  if found_count < 2 then
    raise notice 'Apenas % das 2 contas foi encontrada em Authentication > Users.', found_count;
  else
    raise notice 'As 2 contas administrativas foram encontradas e configuradas.';
  end if;
end $$;

-- =========================================================
-- 25. CONFERIR ADMINS
-- =========================================================
select
  u.id as auth_id,
  u.email as auth_email,
  p.id as profile_id,
  p.email as profile_email,
  p.full_name,
  p.role
from auth.users u
left join public.profiles p on p.id = u.id
where p.role = 'admin'
order by u.email;

-- =========================================================
-- FINAL
-- =========================================================
select 'JMG STORE atualizada com sucesso!' as mensagem;
